version: "3.9"

services:
  db:
    container_name: movieholic_mysql
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "movies"
      MYSQL_USER: "movies_user"
      MYSQL_PASSWORD: "P@ssword1"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
  web:
    container_name: movieholic_backend
    build: .
    volumes:
      - .:/movieholic/backend
    ports:
      - "8000:8000"
    command:
      - bash
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        gunicorn app.wsgi -w 12 -b 0.0.0.0:8000
    depends_on:
      - db